spring.application.name=urlshorten
#management.endpoint.health.show-details=always
#management.endpoints.web.exposure.include=health,info,auditevents,metrics,loggers, beans, mappings,threaddump,env
#management.info.env.enabled=true
#info.app.name=${spring.application.name}
#info.app.description=URL Shortener Application and Event Clicking counter service
#info.app.version=1.0.0 SNAPSHOT
#spring.security.user.name=Mark Tadros
#spring.security.user.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shorten
spring.datasource.username=url_app
spring.datasource.password=urlpasswordfordevelop

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#Turn off the spring boot banner
spring.main.banner-mode=off

#Reduce the logging level to warn
#logging.level.root=warn